# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-10 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleColum',
            new_name='ArticleColumn',
        ),
    ]
